In [1]:
import pandas as pd
import json
import ast

### Cargo las base de datos

In [20]:
data = []
with open(r'Dataset\\output_steam_games.json', 'r', encoding='utf-8') as file:
    for line in file:
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError:
            continue  # Skip the line if it can't be parsed

In [21]:
df = pd.DataFrame(data)
df

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns"
120444,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,NaN,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN

In [22]:
df = df.dropna()
df

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
88310,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro
88311,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,2018-01-04,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,False,643980,Secret Level SRL
88312,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,2017-07-24,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,False,670290,Poolians.com
88313,å½¼å²¸é¢†åŸŸ,"[Action, Adventure, Casual]",å¼¹ç‚¸äºº2222,å¼¹ç‚¸äºº2222,http://store.steampowered.com/app/767400/2222/,2017-12-07,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,å½¼å²¸é¢†åŸŸ
88315,Trickjump Games Ltd,"[Action, Adventure, Simulation]",Battle Royale Trainer,Battle Royale Trainer,http://store.steampowered.com/app/772540/Battl...,2018-01-04,"[Action, Adventure, Simulation, FPS, Shooter, ...",http://steamcommunity.com/app/772540/reviews/?...,"[Single-player, Steam Achievements]",3.99,False,772540,Trickjump Games Ltd
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120439,Bidoniera Games,"[Action, Adventure, Casual, Indie]",Kebab it Up!,Kebab it Up!,http://store.steampowered.com/app/745400/Kebab...,2018-01-04,"[Action, Indie, Casual, Violent, Adventure]",http://steamcommunity.com/app/745400/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",1.99,False,745400,Bidoniera Games
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns"

In [23]:
df1 = df.copy()

In [27]:
# Creo el dataframe con las columnas que nesecito para poder crear las funciones.
df2 = df1[['developer','id', 'release_date', 'price']].copy()
df2

                       developer      id release_date         price
88310                  Kotoshiro  761140   2018-01-04          4.99
88311           Secret Level SRL  643980   2018-01-04  Free To Play
88312               Poolians.com  670290   2017-07-24  Free to Play
88313                       å½¼å²¸é¢†åŸŸ  767400   2017-12-07          0.99
88315        Trickjump Games Ltd  772540   2018-01-04          3.99
...                          ...     ...          ...           ...
120439           Bidoniera Games  745400   2018-01-04          1.99
120440        Nikita "Ghost_RUS"  773640   2018-01-04          1.99
120441                    Sacada  733530   2018-01-04          4.99
120442  Laush Dmitriy Sergeevich  610660   2018-01-04          1.99
120443             xropi,stev3ns  658870   2017-09-02          4.99

[22530 rows x 4 columns]

### Normalizo la columna price... Free to play y free to use lo volvemos a valor 0.

In [28]:
df2['price'] = df2['price'].replace('Free to Play', 0)

In [29]:
df2['price'] = df2['price'].replace('Free to Use', 0)

In [31]:
df2['price'] = df2['price'].replace('Free To Play', 0)

In [32]:
df2['price'] = df2['price'].replace('Free To Use', 0)

In [33]:
df2

                       developer      id release_date price
88310                  Kotoshiro  761140   2018-01-04  4.99
88311           Secret Level SRL  643980   2018-01-04     0
88312               Poolians.com  670290   2017-07-24     0
88313                       å½¼å²¸é¢†åŸŸ  767400   2017-12-07  0.99
88315        Trickjump Games Ltd  772540   2018-01-04  3.99
...                          ...     ...          ...   ...
120439           Bidoniera Games  745400   2018-01-04  1.99
120440        Nikita "Ghost_RUS"  773640   2018-01-04  1.99
120441                    Sacada  733530   2018-01-04  4.99
120442  Laush Dmitriy Sergeevich  610660   2018-01-04  1.99
120443             xropi,stev3ns  658870   2017-09-02  4.99

[22530 rows x 4 columns]

In [34]:
#Cambio el nombre de la columna 'id' por el de 'item_id' para poder hacer el merge con los archivos procesados
# 'developer_db' y 'user_reviews'.  
df2 =df2.rename(columns={'id':'item_id'})
df2

                       developer item_id release_date price
88310                  Kotoshiro  761140   2018-01-04  4.99
88311           Secret Level SRL  643980   2018-01-04     0
88312               Poolians.com  670290   2017-07-24     0
88313                       å½¼å²¸é¢†åŸŸ  767400   2017-12-07  0.99
88315        Trickjump Games Ltd  772540   2018-01-04  3.99
...                          ...     ...          ...   ...
120439           Bidoniera Games  745400   2018-01-04  1.99
120440        Nikita "Ghost_RUS"  773640   2018-01-04  1.99
120441                    Sacada  733530   2018-01-04  4.99
120442  Laush Dmitriy Sergeevich  610660   2018-01-04  1.99
120443             xropi,stev3ns  658870   2017-09-02  4.99

[22530 rows x 4 columns]

In [40]:
# Elimino las filas en release date que tengan valores SOON.
df2 = df2[df2['release_date'] != 'SOON']

In [42]:
df2 = df2[df2['release_date'] != 'SOONâ„¢']

In [43]:
df2['release_date'] = pd.to_datetime(df2['release_date'], format='mixed')

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22528 entries, 88310 to 120443
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   developer     22528 non-null  object
 1   item_id       22528 non-null  object
 2   release_date  22528 non-null  datetime64[ns]
 3   price         22528 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 880.0+ KB

In [45]:
df2.to_csv(r'Dataset\Procesado\developer_db.csv', index=False)

In [50]:
#Cargo el archivo developer_db para hacer un merge con la base de datos
dfs = pd.read_csv(r'Dataset\Procesado\sentiment.csv')

In [53]:
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59305 entries, 0 to 59304
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   59305 non-null  float64
 1   malo      59305 non-null  int64
 2   neutral   59305 non-null  int64
 3   positivo  59305 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 1.8 MB

In [54]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22528 entries, 88310 to 120443
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   developer     22528 non-null  object
 1   item_id       22528 non-null  object
 2   release_date  22528 non-null  datetime64[ns]
 3   price         22528 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 880.0+ KB

In [58]:
#convierto la columna 'item_id' al tipo int
df2['item_id'] = df2['item_id'].astype(int)
dfs['item_id'] = dfs['item_id'].astype(int)

In [59]:
# Hago un merge de los dos archivos utilizando item_id como columna comun.
dev_df = pd.merge(dfs, df2, on='item_id', how='inner')

In [60]:
dev_df

,item_id,malo,neutral,positivo,developer,release_date,price
0,1250,0,0,1,Tripwire Interactive,2009-05-14,19.99
1,22200,0,0,1,ACE Team,2009-04-21,9.99
2,227300,0,0,1,SCS Software,2013-01-16,19.99
3,239030,0,0,1,3909,2013-08-08,9.99
4,248820,0,0,1,"Hopoo Games, LLC",2013-11-08,9.99
...,...,...,...,...,...,...,...
49052,70,0,0,1,Valve,1998-11-08,9.99
49053,362890,0,0,1,Crowbar Collective,2015-05-05,19.99
49054,273110,0,0,1,Nexon,2014-10-07,0
49055,730,0,0,1,Valve,2012-08-21,14.99
49056,440,0,0,1,Valve,2007-10-10,0

In [61]:
#Salvo el dataframe para utilizarlo en las consultas en la api.
dev_df.to_csv(r'Dataset\Procesado\dev_db.csv')